---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
---
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
---
  implicit:
  - Магазин — это SPA приложение, которое не перезагружает страницу
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, 
  - На странице корзины пользователь может оформить заказ с переходом на страницу оплаты 
  - Корзина хранится в сессии браузера 
  - Итоговая сумма заказа рассчитывается корректно
  - При добавлении товара в корзину появляется сообщение  об успешном добавлении товара в корзину
  - При подтверждении заказа все данные о заказе отправляются на сервер
  - После подтверждения заказа появляется сообщение об успешном оформлении заказа
  - Нельзя оформить пустой заказ: без товаров, с нулевым количеством товаров или нулевой суммой
  - В списке заказов отображаются оформленные заказы с указанием названия, количества, цены со скидкой и без
  - В просмотре заказа отображаются заказанные товары, которые относятся к этому заказу
  - Мультиязычность на сайте
