---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
---
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
---
  implicit:
  - Магазин — это SPA приложение, которое не перезагружает страницу
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в каталоге
  - На странице корзины пользователь может удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
  - Корзина хранится в сессии браузера
  - В списке товаров кнопка «Заказать» открывает модальное окно с возможностью ввести количество товара и кнопкой добавления товара в корзину
  - При добавлении товара в корзину появляется сообщение в углу об успешном добавлении товара в корзину
14.	При переходе в корзину показывается список добавленных товаров и кнопка заказа товаров
15.	При нажатии на кнопку заказа товаров в корзине открывается модальное окно с подтверждением заказа
16.	При подтверждении заказа все данные о заказе отправляются на сервер
17.	После подтверждения заказа появляется сообщение об успешном оформлении заказа
18.	Нельзя оформить пустой заказ: без товаров, с нулевым количеством товаров или нулевой суммой
19.	Нельзя добавить товары в корзину пользователям, которые не авторизованы
20.	При просмотре корзины с другого браузера, в корзине отображаются добавленные товары
21.	Нельзя просматривать корзину другого пользователя
22.	В списке заказов отображаются оформленные заказы. Для каждого товара выводится его номер, дата, кнопка просмотра заказа
23.	В просмотре заказа отображаются заказанные товары, которые относятся к этому заказу

